apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.neo4j.nameOverride }}-credentials
  labels:
    app: {{ .Values.neo4j.nameOverride }}
type: Opaque
data:
  neo4j-user: {{ .Values.neo4j.neo4j.user | b64enc }}
  neo4j-password: {{ .Values.neo4j.neo4j.password | b64enc }}