environments: 
  libreconnect-local:
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
---
releases:
  - name: apps
    namespace: {{ .Environment.Name }}
    chart: ../../charts/apps
    values:
      - ./{{ .Environment.Name }}/apps.yaml
  - name: infrastructure
    namespace: {{ .Environment.Name }}
    chart: ../../charts/infra
    values:
      - ./{{ .Environment.Name }}/infrastructure.yaml
