name: Check Service (fmt, clippy)

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      repository:
        type: string
        required: true
    secrets:
      PAT:
        required: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          repository: ${{ inputs.repository }}
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          fetch-tags: true
      - name: Cacho cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo fmt
        run: cargo fmt -- --check 
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          repository: ${{ inputs.repository }}
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          fetch-tags: true
      - name: Cacho cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings